name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.23.2

      - run: deno --version

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Typecheck
        run: deno check ./tools-39.ts
